# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [11]:
print(np.__version__)

1.23.0rc1


#### 3. Create a null vector of size 10 (★☆☆)

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
from sys import getsizeof
a = np.ones(100)
print("size of numeric element - ", a.nbytes)
print("size of numeric element and machinery - ", getsizeof(a))

size of numeric element -  800
size of numeric element and machinery -  896


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
b = np.zeros(10)
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
c = np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
d = np.flip(c)
d

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
e = np.arange(0,9).reshape(3,3)
e 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
f = [1,2,0,0,4,0]
non_zero = []
for i in range(len(f)):
    if f[i] == 0:
        non_zero.append(i)
print("non zero indices array - ",non_zero)

non zero indices array -  [2, 3, 5]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
g = np.ones(9).reshape(3,3)
g

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
h = np.random.random((3,3,3))
h



array([[[0.49889634, 0.33320714, 0.40520867],
        [0.36591921, 0.64652371, 0.74008201],
        [0.64840955, 0.45165815, 0.5982466 ]],

       [[0.46047475, 0.56472075, 0.32542109],
        [0.74299653, 0.21864155, 0.760611  ],
        [0.13175303, 0.54031398, 0.14215522]],

       [[0.93778736, 0.90161951, 0.80135735],
        [0.52986046, 0.44035425, 0.04040481],
        [0.08267705, 0.40574008, 0.04417186]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
i = np.random.random((10,10))
print("minimum value - ", i.min())
print("max value - ",i.max())

minimum value -  0.006014466080318637
max value -  0.9709279991187105


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [20]:
j = np.random.random(30)
print("mean value - ",j.mean())

mean value -  0.5102302237336608


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [28]:
k = np.zeros(8).reshape(2,4)
for i in range(len(k)):
    k[i][-1] = 1
    k[i][0] = 1 
k

array([[1., 0., 0., 1.],
       [1., 0., 0., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [29]:
l = np.pad(k, pad_width=1, mode='constant', constant_values=0)
l

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [30]:
print(0*np.nan)

nan


In [31]:
print(np.nan == np.nan)

False


In [32]:
print(np.inf>np.nan)

False


In [33]:
print(np.nan-np.nan)

nan


In [34]:
print(np.nan in set([np.nan]))

True


In [36]:
print(0.3 == 3*0.1)

False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [41]:
m = np.diag(1+np.arange(4),k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [43]:
n = np.zeros((5,5),dtype=int)
n[1::2,::2] = 1
n[::2,1::2] = 1
print("checkerboard pattern - ")
print(n)

checkerboard pattern - 
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [53]:
x,y,z = np.unravel_index(99,(6,7,8))
print(f"index value {x},{y},{z}")

index value 1,5,3


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [54]:
p = [1,0,1,0,1]
np.tile(p,(3,3))

array([[1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [55]:
norm_arr = np.random.random((5,5))
(norm_arr - np.mean(norm_arr)/np.std(norm_arr))

array([[-1.90217344, -1.29229696, -1.10338996, -1.03882784, -1.13154386],
       [-1.73111088, -1.86362509, -1.37503047, -1.73196888, -1.49541611],
       [-1.46413673, -1.19828786, -1.14509278, -1.86193241, -1.14843923],
       [-1.5704042 , -1.04503905, -1.78072599, -1.14346938, -1.33220413],
       [-1.52782637, -1.8225312 , -1.04092284, -1.37155132, -1.45480432]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [56]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [62]:
arr_a = np.ones(15)
arr_a = arr_a.reshape(5,3)
arr_b = np.arange(6)
arr_b = arr_b.reshape(3,2)
arr_c = np.dot(arr_a,arr_b)
arr_c

array([[6., 9.],
       [6., 9.],
       [6., 9.],
       [6., 9.],
       [6., 9.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [63]:
arr = np.arange(10)
arr[(3 < arr) & (arr < 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [66]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [67]:
z = np.arange(5)

In [68]:
z**z  #possible

array([  1,   1,   4,  27, 256], dtype=int32)

In [71]:
2 << z >> 2 #are bit shift operators (left and right, respectively)

array([0, 1, 2, 4, 8], dtype=int32)

In [72]:
z< -z #compare elementwise

array([False, False, False, False, False])

In [73]:
1j*z  #add imaginery axis

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [74]:
z/1/1

array([0., 1., 2., 3., 4.])

In [75]:
z<z>z  #not ppossible

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [76]:
np.array(0)/np.array(0)  

<ipython-input-76-b5ef8fbb8689>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0)/np.array(0)


nan

In [77]:
np.array(0)//np.array(0)

<ipython-input-77-e72bfd15dca1>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0)//np.array(0)


0

#### 29. How to round away from zero a float array ? (★☆☆)

In [87]:
arr = np.arange(start=-2,step=0.05,stop=3,dtype=float)
np.copysign(np.ceil(np.abs(arr)), arr)

array([-2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2.,
       -2., -2., -2., -2., -2., -2., -2., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [91]:
arr_a = np.random.randint(5,10,5)
arr_b = np.random.randint(5,10,5)
np.intersect1d(arr_a,arr_b)

array([5, 7])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [92]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [93]:
np.sqrt(-1) == np.emath.sqrt(-1)  #Different results are expected because: floating point 0.0 and -0.0 are distinct

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [94]:
print("yesterday was ", np.datetime64('today') - np.timedelta64(1))
print ("today is ", np.datetime64('today'))
print("tomorrow will be ", np.datetime64('today') + np.timedelta64(1))

yesterday was  2024-05-29
today is  2024-05-30
tomorrow will be  2024-05-31


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [95]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]') #choose date from month

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [99]:
A = np.ones(3)*2
B = np.ones(3)*3
np.add(A,B,out=B)     #use out option to store the computed result in place 
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-5., -5., -5.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [102]:
arr = np.random.uniform(0,10,10)
arr

array([1.01524479, 9.22839567, 3.16330909, 3.49198021, 0.24443897,
       6.96452457, 2.50607888, 4.51751343, 6.29542081, 3.72986167])

In [103]:
arr - arr%1

array([1., 9., 3., 3., 0., 6., 2., 4., 6., 3.])

In [104]:
arr//1 #only reminder 

array([1., 9., 3., 3., 0., 6., 2., 4., 6., 3.])

In [105]:
np.floor(arr) #round to lower value

array([1., 9., 3., 3., 0., 6., 2., 4., 6., 3.])

In [106]:
arr.astype(int) #change datatype 

array([1, 9, 3, 3, 0, 6, 2, 4, 6, 3])

In [107]:
np.trunc(arr) 

array([1., 9., 3., 3., 0., 6., 2., 4., 6., 3.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [108]:
np.tile(np.arange(0, 5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [109]:
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(),dtype=float,count=-1) #Create a new 1-dimensional array from an iterable object.

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [110]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [112]:
arr = np.random.random(10)
arr.sort()
arr

array([0.02311402, 0.06441763, 0.07564466, 0.0818948 , 0.24341654,
       0.55023249, 0.66568121, 0.7045827 , 0.71100573, 0.77618497])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [4]:
import timeit
arr_sum = np.random.random(5)
starttime = timeit.timeit()
new_sum = np.sum(arr_sum)
print("total time ", timeit.timeit()-starttime)
starttime1 = timeit.timeit()
new_sum = np.add.reduce(arr_sum)
print("total time ", timeit.timeit()-starttime1)

total time  -0.000530900000001111
total time  -7.379999996715014e-05


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [6]:
A = np.random.randint(0,5,5)
B = np.random.randint(0,5,5)
check = np.allclose(A,B)
check

False

#### 43. Make an array immutable (read-only) (★★☆)

In [7]:
arr = np.zeros(5)
arr.flags.writeable = False   #makes it readonly
arr[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [8]:
Z = np.random.random((10,2)) 
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.90929853 0.12343707 0.20222578 0.93737872 0.12652178 1.10145091
 0.56680974 0.5136614  0.69051566 0.43169141]
[0.36268867 0.07508813 0.35382915 0.26717066 0.97762491 0.44597679
 1.27678288 1.07201002 1.12362829 0.39758369]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [21]:
arr = np.random.random(10)
print(arr)
np.where(arr != np.max(arr), arr, 0)


[0.05536171 0.37429648 0.51695741 0.65722186 0.37665297 0.49803407
 0.56163433 0.63164848 0.75011669 0.42146462]


array([0.05536171, 0.37429648, 0.51695741, 0.65722186, 0.37665297,
       0.49803407, 0.56163433, 0.63164848, 0.        , 0.42146462])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [22]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr #array of 5x5 float

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [24]:
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5)) #Return a list of coordinate matrices from coordinate vectors
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [25]:
X = np.arange(5)
Y = X+0.05
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C)) #Compute the determinant of an array

-3240575.092694402


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [26]:
#integer 
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)  #Machine limits for integer point types
   print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [27]:
#float 
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)  #Machine limits for floating point types
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [29]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [30]:
arr = np.arange(50)
num = np.random.uniform(0,50)
i = (np.abs(arr-num)).argmin()
arr[i]

31

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [31]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-31-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [32]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)  #Compute distance between each pair of the two collections of inputs.
print(D)

[[0.         0.20576717 0.90961967 0.22480336 0.31279186 0.91359986
  0.91535131 0.56844147 0.40083213 0.98331625]
 [0.20576717 0.         0.78289994 0.04715633 0.11165352 0.75829312
  0.71010953 0.37803798 0.37217088 0.90165359]
 [0.90961967 0.78289994 0.         0.81388034 0.69721355 0.16087653
  0.66999466 0.49373005 0.55151387 0.24676614]
 [0.22480336 0.04715633 0.81388034 0.         0.1231589  0.78149752
  0.70078638 0.38875172 0.4186454  0.94047663]
 [0.31279186 0.11165352 0.69721355 0.1231589  0.         0.65911364
  0.60348795 0.2675876  0.36379783 0.83750116]
 [0.91359986 0.75829312 0.16087653 0.78149752 0.65911364 0.
  0.51875169 0.41650291 0.60314168 0.40702841]
 [0.91535131 0.71010953 0.66999466 0.70078638 0.60348795 0.51875169
  0.         0.39085017 0.8183611  0.91344314]
 [0.56844147 0.37803798 0.49373005 0.38875172 0.2675876  0.41650291
  0.39085017 0.         0.43018908 0.68774719]
 [0.40083213 0.37217088 0.55151387 0.4186454  0.36379783 0.60314168
  0.8183611  0.43018

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [33]:
arr = (np.random.rand(10)*100).astype(np.float32)
Y = arr.view(np.int32)
Y[:] = arr
print(Y)

[76 58  9 44 53 21 47 88 45  4]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [34]:
from io import StringIO

In [35]:
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')

In [36]:
np.genfromtxt(s, delimiter=",", dtype=np.int)

<ipython-input-36-184abcb6aa1e>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.genfromtxt(s, delimiter=",", dtype=np.int)


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [37]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):  #Multidimensional index iterator
    print(index, value)
for index in np.ndindex(Z.shape):       #An N-dimensional iterator object to index arrays.
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [38]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

In [39]:
D = np.sqrt(X*X+Y*Y)
D

array([[1.41421356, 1.26686158, 1.1439589 , 1.05409255, 1.0061539 ,
        1.0061539 , 1.05409255, 1.1439589 , 1.26686158, 1.41421356],
       [1.26686158, 1.09994388, 0.95581392, 0.84619701, 0.7856742 ,
        0.7856742 , 0.84619701, 0.95581392, 1.09994388, 1.26686158],
       [1.1439589 , 0.95581392, 0.7856742 , 0.64788354, 0.56655772,
        0.56655772, 0.64788354, 0.7856742 , 0.95581392, 1.1439589 ],
       [1.05409255, 0.84619701, 0.64788354, 0.47140452, 0.35136418,
        0.35136418, 0.47140452, 0.64788354, 0.84619701, 1.05409255],
       [1.0061539 , 0.7856742 , 0.56655772, 0.35136418, 0.15713484,
        0.15713484, 0.35136418, 0.56655772, 0.7856742 , 1.0061539 ],
       [1.0061539 , 0.7856742 , 0.56655772, 0.35136418, 0.15713484,
        0.15713484, 0.35136418, 0.56655772, 0.7856742 , 1.0061539 ],
       [1.05409255, 0.84619701, 0.64788354, 0.47140452, 0.35136418,
        0.35136418, 0.47140452, 0.64788354, 0.84619701, 1.05409255],
       [1.1439589 , 0.95581392, 0.7856742

In [40]:
#initiate 
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [41]:
n = 5
p = 2
arr = np.zeros((n,n))
np.put(arr,np.random.choice(range(n*n),p,replace=False),1)
print(arr)

[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [44]:
arr = np.random.rand(5, 10)
arr = arr - arr.mean(axis=1, keepdims=True)
arr

array([[ 0.27618315, -0.34923245, -0.28509317,  0.32568894,  0.34156534,
        -0.4549064 ,  0.31705421, -0.09736803, -0.09789991,  0.02400831],
       [ 0.04904432, -0.14423075, -0.28052921,  0.01348414,  0.53785611,
        -0.40610791,  0.30082801, -0.04927498, -0.29159122,  0.2705215 ],
       [ 0.27720183, -0.00340472,  0.16073288,  0.38565154,  0.4639587 ,
        -0.10461743, -0.29149286, -0.31683749, -0.28580764, -0.28538481],
       [ 0.24853665,  0.38637254, -0.43143327,  0.17552586, -0.49697058,
         0.31812503, -0.27342015,  0.11738321,  0.08118695, -0.12530625],
       [ 0.25638023, -0.46285495,  0.49870453,  0.34681875, -0.42442996,
         0.10297237, -0.18924374,  0.05098348,  0.00235707, -0.18168779]])

#### 59. How to sort an array by the nth column? (★★☆)

In [45]:
arr = np.random.randint(0,10,(3,3))
arr

array([[0, 1, 6],
       [2, 7, 8],
       [9, 6, 3]])

In [47]:
arr[arr[:,1].argsort()]

array([[0, 1, 6],
       [9, 6, 3],
       [2, 7, 8]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [56]:
arr = np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
np.isnan(arr)

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [57]:
np.isnan(arr).all(axis=0)

array([False, False,  True])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [65]:
arr = np.random.uniform(0,10,10)
arr

array([3.46225633, 7.75644625, 7.10589561, 4.71065076, 0.29275747,
       0.60869878, 0.97647761, 9.87580992, 1.66615749, 9.94504514])

In [66]:
diff = 0.25
res = arr.flat[np.abs(arr-diff).argmin()]
res

0.2927574672731781

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [67]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

In [70]:
print(A)
print(B)

[[0]
 [1]
 [2]]
[[0 1 2]]


In [69]:
it = np.nditer([A,B,None])   # Efficient multi-dimensional iterator object to iterate over arrays
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [71]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

In [72]:
arr = NamedArray(np.arange(10), "range_10")
print (arr.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [73]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)

In [75]:
Z += np.bincount(I, minlength=len(Z)) #Count number of occurrences of each value in array of non-negative ints
print(Z)

[3. 2. 2. 5. 2. 3. 4. 1. 3. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [76]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [77]:
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

In [78]:
I24 = np.dot(I.astype(np.uint32),[1,256,65536]) 
n = len(np.unique(I24))
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [80]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[63 60 41 56]
 [51 66 60 61]
 [38 68 58 44]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [81]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

In [82]:
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.348738
1    0.315598
2    0.581555
3    0.653634
4    0.515962
5    0.422982
6    0.454408
7    0.276692
8    0.405516
9    0.523221
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [83]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [84]:
np.diag(np.dot(A, B))

array([2.02935228, 0.74338337, 1.00512176, 1.18931433, 0.61103409])

In [85]:
np.sum(A * B.T, axis=1)

array([2.02935228, 0.74338337, 1.00512176, 1.18931433, 0.61103409])

In [86]:
np.einsum("ij,ji->i", A, B)  #fastest

array([2.02935228, 0.74338337, 1.00512176, 1.18931433, 0.61103409])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [87]:
arr = np.array([1,2,3,4,5])
num_zeros = 3
arr_z = np.zeros(len(arr) + (len(arr)-1)*(num_zeros))
arr_z[::num_zeros+1] = arr
print(arr_z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [88]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))

In [90]:
B[:,:,None].shape

(5, 5, 1)

In [91]:
A*B[:,:,None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [92]:
arr = np.arange(9).reshape(3,3)
arr[[0,1]] = arr[1,0]
arr

array([[3, 3, 3],
       [3, 3, 3],
       [6, 7, 8]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [95]:
faces = np.random.randint(0,100,(10,3)) #populate triangle vertices
F = np.roll(faces.repeat(2,axis=1),-1,axis=1) #np.roll rotate the element, np.repeat repeat the array, similar to np.tile
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(12, 14) (12, 78) (12, 81) (12, 90) (14, 69) (14, 77) (14, 81) (15, 49)
 (15, 86) (16, 18) (16, 33) (18, 33) (21, 22) (21, 29) (22, 29) (23, 33)
 (23, 90) (26, 50) (26, 84) (30, 46) (30, 80) (33, 90) (46, 80) (49, 86)
 (50, 84) (63, 94) (63, 99) (69, 77) (78, 90) (94, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [96]:
C = np.bincount([1,1,2,3,4,4,6])  # 0 occurs 0times, 1 occurs 2times, 2 occurs 1 , and so
C

array([0, 2, 1, 1, 2, 0, 1], dtype=int64)

In [97]:
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 4, 4, 6])

In [98]:
np.bincount(A) == C

array([ True,  True,  True,  True,  True,  True,  True])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [99]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)   #Return the cumulative sum of the elements along a given axis.
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [101]:
arr = np.arange(10)
moving_average(arr,n=4)

array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [102]:
from numpy.lib import stride_tricks

In [104]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

In [105]:
arr = rolling(np.arange(10), 3)
arr

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [106]:
arr = np.random.uniform(-5,5,20)
np.negative(arr,out=arr)

array([ 1.91584653,  4.85933432, -0.49573024, -4.78109822,  2.80942816,
        4.27354058, -1.84892188, -2.90345082,  2.97706274, -1.30897161,
       -2.33255269, -2.52124429,  0.24032601, -4.21339734,  4.02467169,
        3.43442444, -3.71266595,  4.31262565, -2.25602793, -2.62098555])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [125]:
def point_to_line_distance(P0, P1, p):
    x0, y0 = p[0][0],p[0][1]
    distances = []
    for i in range(len(P0)):
        x1, y1 = P0[i][0],P0[i][1]
        x2, y2 = P1[i][0],P1[i][1]
        numerator = abs((y2 - y1) * x0 - (x2 - x1) * y0 + x2 * y1 - y2 * x1)
        denominator = np.sqrt((y2 - y1)**2 + (x2 - x1)**2)
        distance = numerator / denominator
        distances.append(distance)
    return distances

In [126]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

distance = []
# for i in range(len(P0)):
distance = point_to_line_distance(P0,P1,p)
distance 


[6.460927840321175,
 4.897602107306447,
 6.752306613711915,
 0.4702152944891119,
 2.501930409334737,
 8.69764354538598,
 1.452089624668688,
 5.719249103703023,
 1.2029686594365627,
 6.075253686426663]

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [131]:
def point_to_line_distance(P0, P1, p):
    x0, y0 = p[0],p[1]
    distances = []
    for i in range(len(P0)):
        x1, y1 = P0[i][0],P0[i][1]
        x2, y2 = P1[i][0],P1[i][1]
        numerator = abs((y2 - y1) * x0 - (x2 - x1) * y0 + x2 * y1 - y2 * x1)
        denominator = np.sqrt((y2 - y1)**2 + (x2 - x1)**2)
        distance = numerator / denominator
        distances.append(distance)
    return distances
    

In [132]:
p2  = np.random.uniform(-10,10,(10,2))
distance_new = []
for j in range(len(p2)):
    distance_new.append(point_to_line_distance(P0,P1,p2[j]))
distance_new

[[2.8457111407323703,
  4.472368892883614,
  10.216326217979299,
  2.7967863164700666,
  1.3768566092218806,
  13.23723200142791,
  3.197558237713598,
  9.339271703902119,
  1.9386556009693785,
  2.320613963847573],
 [14.441228916434254,
  7.938055960356223,
  1.9013576010449285,
  5.731528526739413,
  8.39628912858574,
  0.27094196257423003,
  3.834626774337301,
  0.48653652426333843,
  8.583149681087242,
  14.213645169107375],
 [9.032286353855508,
  4.730483907876004,
  8.920173724996596,
  3.852183087558892,
  17.865380109686143,
  2.062889668608153,
  6.984730000872324,
  9.887484576536199,
  1.3335348595798169,
  9.452962884853529],
 [1.299178430336616,
  1.595525467057493,
  6.765399873918206,
  8.294583987248263,
  1.259101160970492,
  14.20956313343446,
  9.005404618359082,
  6.166502347685114,
  6.722855151193228,
  1.5867309075466023],
 [8.560349609581877,
  6.077801755602387,
  5.982020688738627,
  1.3542151920405494,
  3.5698459915467007,
  6.769242349359988,
  0.1981588062

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [133]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [137]:
arr = np.arange(15)[1:]
R = stride_tricks.as_strided(arr,(11,4),(4,4)) #Create a view into the array with the given shape and strides.
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [138]:
arr = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(arr)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [139]:
arr = np.random.randint(0,15,50)
np.bincount(arr).argmax()

3

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [141]:
from numpy.lib.stride_tricks import sliding_window_view

In [142]:
arr = np.random.randint(0,5,(10,10))
print(sliding_window_view(arr, window_shape=(3, 3)))

[[[[0 4 3]
   [3 3 1]
   [4 4 0]]

  [[4 3 3]
   [3 1 1]
   [4 0 3]]

  [[3 3 4]
   [1 1 3]
   [0 3 3]]

  [[3 4 3]
   [1 3 0]
   [3 3 2]]

  [[4 3 0]
   [3 0 2]
   [3 2 4]]

  [[3 0 4]
   [0 2 4]
   [2 4 1]]

  [[0 4 4]
   [2 4 2]
   [4 1 0]]

  [[4 4 1]
   [4 2 1]
   [1 0 3]]]


 [[[3 3 1]
   [4 4 0]
   [4 3 0]]

  [[3 1 1]
   [4 0 3]
   [3 0 2]]

  [[1 1 3]
   [0 3 3]
   [0 2 1]]

  [[1 3 0]
   [3 3 2]
   [2 1 3]]

  [[3 0 2]
   [3 2 4]
   [1 3 2]]

  [[0 2 4]
   [2 4 1]
   [3 2 0]]

  [[2 4 2]
   [4 1 0]
   [2 0 3]]

  [[4 2 1]
   [1 0 3]
   [0 3 2]]]


 [[[4 4 0]
   [4 3 0]
   [1 4 2]]

  [[4 0 3]
   [3 0 2]
   [4 2 1]]

  [[0 3 3]
   [0 2 1]
   [2 1 1]]

  [[3 3 2]
   [2 1 3]
   [1 1 0]]

  [[3 2 4]
   [1 3 2]
   [1 0 0]]

  [[2 4 1]
   [3 2 0]
   [0 0 4]]

  [[4 1 0]
   [2 0 3]
   [0 4 4]]

  [[1 0 3]
   [0 3 2]
   [4 4 4]]]


 [[[4 3 0]
   [1 4 2]
   [1 1 2]]

  [[3 0 2]
   [4 2 1]
   [1 2 1]]

  [[0 2 1]
   [2 1 1]
   [2 1 1]]

  [[2 1 3]
   [1 1 0]
   [1 1 0]]

  [[1 3 2]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [144]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

In [145]:
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

In [146]:
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2 10 12  2  9]
 [10  8  7  8 12]
 [12  7  1 42  6]
 [ 2  8 42  9 11]
 [ 9 12  6 11  7]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [147]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]]) #Compute tensor dot product along specified axes.
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [148]:
Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

In [149]:
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
#life is life cant solve with numpy

#### 89. How to get the n largest values of an array (★★★)

In [157]:
arr = np.random.rand(1,10)
arr.max()

0.9800506366647413

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [158]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

In [159]:
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [160]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [161]:
x = np.random.rand(int(5e7))

In [162]:
%timeit np.power(x,3)

1.9 s ± 598 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [163]:
%timeit x*x*x

471 ms ± 110 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [164]:
%timeit np.einsum('i,i,i->i',x,x,x)

324 ms ± 77.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [165]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

In [166]:
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [167]:
Z = np.random.randint(0,5,(10,3))
print(Z)

[[0 4 3]
 [1 3 3]
 [4 3 3]
 [2 3 3]
 [0 3 3]
 [0 2 4]
 [1 0 2]
 [3 1 4]
 [2 4 0]
 [2 0 4]]


In [168]:
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 4 3]
 [1 3 3]
 [4 3 3]
 [2 3 3]
 [0 3 3]
 [0 2 4]
 [1 0 2]
 [3 1 4]
 [2 4 0]
 [2 0 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [169]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [170]:
Z = np.random.randint(0,2,(6,3))
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [171]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

In [173]:
np.einsum('i->', A)       # np.sum(A)

3.1175974865023504

In [174]:
np.einsum('i,i->i', A, B) # A * B mul

array([0.17168447, 0.05897352, 0.04968603, 0.23380663, 0.13254002,
       0.07659234, 0.01705773, 0.51083765, 0.00339377, 0.49277456])

In [175]:
np.einsum('i,i', A, B)    # np.inner(A, B)

1.7473467410059829

In [176]:
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.17168447, 0.12441306, 0.10402417, 0.21150278, 0.13126963,
        0.11441661, 0.02456905, 0.25139225, 0.07102553, 0.25135233],
       [0.08138084, 0.05897352, 0.04930891, 0.10025527, 0.06222363,
        0.05423507, 0.01164607, 0.11916343, 0.03366709, 0.11914451],
       [0.08200326, 0.05942457, 0.04968603, 0.10102204, 0.06269953,
        0.05464987, 0.01173515, 0.12007482, 0.03392459, 0.12005575],
       [0.18978932, 0.13753293, 0.11499396, 0.23380663, 0.14511256,
        0.12648232, 0.02715996, 0.27790262, 0.07851547, 0.27785848],
       [0.17334599, 0.12561709, 0.10503089, 0.21354965, 0.13254002,
        0.1155239 , 0.02480682, 0.25382516, 0.0717129 , 0.25378485],
       [0.11492838, 0.08328413, 0.06963548, 0.14158341, 0.08787403,
        0.07659234, 0.01644692, 0.16828607, 0.04754565, 0.16825934],
       [0.11919658, 0.08637713, 0.07222159, 0.14684152, 0.09113748,
        0.07943682, 0.01705773, 0.17453586, 0.0493114 , 0.17450814],
       [0.34886872, 0.25281158, 0.2113806

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [177]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

In [178]:
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [179]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])

In [180]:
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [181]:
X = np.random.randn(100) # random 1D array

In [182]:
N = 1000 # number of bootstrap samples

In [183]:
idx = np.random.randint(0, X.size, (N, X.size))

In [184]:
means = X[idx].mean(axis=1)

In [185]:
confint = np.percentile(means, [2.5, 97.5])

In [186]:
print(confint)

[-0.17979622  0.17646877]


In [ ]:
#did it